import SiteShell from "@/components/SiteShell";
import { CircleHelp, FileCheck2, LockKeyhole, PlaySquare } from "lucide-react";

const faqs = [
  ["Which links work?", "TubeTranscriber accepts standard YouTube watch links, youtu.be links, Shorts, embed URLs, and an 11-character YouTube video ID."],
  ["Why does a video sometimes have no transcript?", "Transcripts depend on captions being available to YouTube. Private videos, videos with captions disabled, and some restricted videos cannot provide transcript text."],
  ["What does TubeTranscriber save?", "When you sign in, we save the video title, channel, thumbnail, video identifier, and time of your lookup to your private history. Transcript text is generated on demand."],
  ["Can I use the downloaded file anywhere?", "Exports are offered for your lawful use. Please respect copyright, the original creator, and the terms governing the source material."],
];

export default function About() { return <SiteShell><section className="about-hero"><div className="content-container"><p className="eyebrow"><CircleHelp size={14} /> Thoughtfully straightforward</p><h1>Useful transcripts,<br /><span>without the noise.</span></h1><p>TubeTranscriber turns available video captions into a practical working document, while keeping the interface focused and your history personal.</p></div></section><section className="about-grid content-container"><article><PlaySquare size={22} /><h2>1. Paste a public YouTube link</h2><p>Use a video, Short, or embedded YouTube URL. We identify the video and retrieve the details needed to present it clearly.</p></article><article><FileCheck2 size={22} /><h2>2. Read and export captions</h2><p>Use search to find a phrase, copy the whole transcript, or download it as TXT, JSON, or SRT.</p></article><article><LockKeyhole size={22} /><h2>3. Keep your library personal</h2><p>With Manus OAuth, completed lookups can be stored exclusively in your own history for convenient re-opening.</p></article></section><section className="faq-section content-container"><div className="section-heading"><p className="eyebrow">Questions, answered</p><h2>Frequently asked questions</h2></div><div className="faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section></SiteShell>; }
