import SiteShell from "@/components/SiteShell";
import { CircleHelp, FileCheck2, LockKeyhole, PlaySquare } from "lucide-react";

const faqs = [
  ["Which links work?", "TubeTranscriber accepts standard YouTube watch links, youtu.be links, Shorts, embed URLs, and an 11-character YouTube video ID."],
  ["Why does a video sometimes have no transcript?", "Transcripts depend on captions being exposed by YouTube. Private videos, videos with captions disabled, and some restricted videos cannot provide transcript text."],
  ["What does TubeTranscriber save?", "TubeTranscriber saves recent video details only in your current browser so you can re-open lookups. You can remove one entry or clear the local history whenever you choose."],
  ["Can I use the downloaded file anywhere?", "Exports are offered for your lawful use. Please respect copyright, the original creator, and the terms governing the source material."],
];

export default function About() { return <SiteShell><section className="about-hero"><div className="content-container"><p className="eyebrow"><CircleHelp size={14} /> Thoughtfully straightforward</p><h1>Clean YouTube transcripts,<br /><span>ready to use.</span></h1><p>Turn any YouTube video into a clean, readable transcript in seconds.</p><p>Paste a YouTube link and get a practical working document—without clutter, unnecessary timestamps, or distracting formatting.</p><p className="about-hero-tagline">Simple. Fast. Useful.</p><p>Your transcript history stays right in your browser, so you can easily find and revisit videos you&apos;ve processed before.</p></div></section><section className="about-grid content-container" aria-labelledby="guide-heading"><article><PlaySquare size={22} /><h2 id="guide-heading">1. Paste a public YouTube link</h2><p>Use a video, Short, or embedded YouTube URL. We identify the video and retrieve the details needed to present it clearly.</p></article><article><FileCheck2 size={22} /><h2>2. Read and export captions</h2><p>Search the plain transcript, copy the whole text, or download it as TXT, JSON, or SRT.</p></article><article><LockKeyhole size={22} /><h2>3. Keep recent work local</h2><p>Completed lookups are stored in your current browser for convenient re-opening, without a sign-in.</p></article></section><section className="faq-section content-container" aria-labelledby="faq-heading"><div className="section-heading"><p className="eyebrow">Questions, answered</p><h2 id="faq-heading">Frequently asked questions</h2></div><div className="faq-list">{faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section></SiteShell>; }
