import { TRPCError } from "@trpc/server";
import type { ExtractedTranscript } from "./transcript";

const DEFAULT_TIMEOUT_MS = 15_000;

export function transcriptWorkerUrl() {
  const direct = (process.env.CF_TRANSCRIPT_WORKER_URL ?? "").trim();
  if (direct) return direct.replace(/\/$/, "");
  const legacy = (process.env.CF_WORKER_PROXY ?? "").trim().replace(/\/$/, "");
  return legacy.replace(/\?url=$/, "");
}

type WorkerCue = { text?: unknown; offset?: unknown; duration?: unknown };
type WorkerPayload = {
  videoId?: unknown;
  title?: unknown;
  author?: unknown;
  authorUrl?: unknown;
  avatar?: unknown;
  language?: { code?: unknown; name?: unknown; isAutoGenerated?: unknown };
  transcript?: WorkerCue[];
  workerCacheStatus?: unknown;
};

const SAFE_WORKER_STAGES = new Set(["watch-fetch", "player-config", "player-fetch", "player-playability", "caption-tracks", "caption-track-url", "timedtext-empty"]);

function workerError(status: number, message: string, stage = ""): never {
  const detail = SAFE_WORKER_STAGES.has(stage) ? ` [Cloudflare stage: ${stage}]` : "";
  const safeMessage = `${message}${detail}`;
  if (status === 400) throw new TRPCError({ code: "BAD_REQUEST", message: safeMessage });
  if (status === 403) throw new TRPCError({ code: "FORBIDDEN", message: safeMessage });
  if (status === 404) throw new TRPCError({ code: "NOT_FOUND", message: safeMessage });
  if (status === 422) throw new TRPCError({ code: "UNPROCESSABLE_CONTENT", message: safeMessage });
  if (status === 429) throw new TRPCError({ code: "TOO_MANY_REQUESTS", message: safeMessage });
  throw new TRPCError({ code: "BAD_GATEWAY", message: safeMessage });
}

export async function extractTranscriptFromWorker(url: string, turnstileToken: string, lang?: string): Promise<ExtractedTranscript> {
  const endpoint = transcriptWorkerUrl();
  if (!endpoint) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "The Cloudflare transcript Worker is not configured." });
  if (!turnstileToken.trim()) throw new TRPCError({ code: "FORBIDDEN", message: "Please complete the security check before extracting captions." });

  const target = new URL(`${endpoint}/api/transcript`);
  target.searchParams.set("url", url);
  if (lang?.trim()) target.searchParams.set("lang", lang.trim());

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), DEFAULT_TIMEOUT_MS);
  try {
    const response = await fetch(target, {
      method: "GET",
      headers: {
        Accept: "application/json",
        "x-turnstile-token": turnstileToken.trim(),
        "Cache-Control": "no-store",
      },
      signal: controller.signal,
    });
    const raw = await response.text();
    let payload: WorkerPayload | { error?: string } = {};
    try { payload = JSON.parse(raw) as WorkerPayload | { error?: string }; } catch { workerError(response.status, "The Cloudflare transcript Worker returned an invalid response."); }
    if (!response.ok) {
      const stage = response.headers.get("x-transcript-stage") || "";
      workerError(response.status, typeof payload === "object" && payload && "error" in payload && typeof payload.error === "string" ? payload.error : "The Cloudflare transcript Worker could not retrieve captions.", stage);
    }

    const success = payload as WorkerPayload;
    const transcript = Array.isArray(success.transcript) ? success.transcript : [];
    const segments = transcript.map(cue => ({
      start: Number(cue.offset || 0) / 1000,
      duration: Number(cue.duration || 0) / 1000,
      text: String(cue.text || "").replace(/\s+/g, " ").trim(),
    })).filter(cue => cue.text);
    if (!success.videoId || !segments.length) throw new TRPCError({ code: "NOT_FOUND", message: "No public captions are available for this video." });

    const language = success.language;
    return {
      metadata: {
        videoId: String(success.videoId),
        title: String(success.title || "YouTube video"),
        channel: String(success.author || "YouTube"),
        thumbnailUrl: String(success.avatar || `https://i.ytimg.com/vi/${success.videoId}/hqdefault.jpg`),
        durationSeconds: segments.at(-1) ? segments.at(-1)!.start + segments.at(-1)!.duration : null,
      },
      segments,
      originalLanguage: language?.code ? {
        code: String(language.code),
        name: String(language.name || language.code),
        isOriginal: true,
        isAutoGenerated: Boolean(language.isAutoGenerated),
      } : undefined,
      workerCacheStatus: success.workerCacheStatus === "HIT" || success.workerCacheStatus === "STORED" || success.workerCacheStatus === "WRITE_FAILED"
        ? success.workerCacheStatus
        : undefined,
    };
  } catch (error) {
    if (error instanceof TRPCError) throw error;
    if (error instanceof Error && error.name === "AbortError") throw new TRPCError({ code: "TIMEOUT", message: "The Cloudflare transcript Worker timed out." });
    throw new TRPCError({ code: "BAD_GATEWAY", message: "The Cloudflare transcript Worker could not be reached." });
  } finally {
    clearTimeout(timeout);
  }
}
