"""Bridge the Node server to YouTube transcript extraction."""

from __future__ import annotations

import html as html_lib
import json
import os
import random
import re
import sys
import time
import xml.etree.ElementTree as ET
from http.cookiejar import MozillaCookieJar
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import requests
try:
    import yt_dlp
except ImportError:  # pragma: no cover - optional dependency in local test environments
    yt_dlp = None

from youtube_transcript_api import (
    NoTranscriptFound,
    TranscriptsDisabled,
    VideoUnavailable,
    YouTubeTranscriptApi,
)
from youtube_transcript_api.formatters import TextFormatter


VIDEO_ID_PATTERN = r"[0-9A-Za-z_-]{11}"
YOUTUBE_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
)
YOUTUBE_CONSENT_COOKIE = "SOCS=CAESEwgDEgk2MTExNDM3NDIaAmVuIAEaBgiA_L2yBg;"


class NoCaptionsError(RuntimeError):
    """Raised when YouTube exposes no usable caption tracks."""


class CaptionPayloadError(RuntimeError):
    """Raised when a caption track exists but its payload is unusable."""


class YouTubeRateLimitError(RuntimeError):
    """Raised when YouTube or the proxy asks the caller to slow down."""


class YtDlpUnavailableError(RuntimeError):
    """Raised when the optional yt-dlp fallback is not installed."""


TranscriptResult = dict[str, Any]


def _language_name(value: Any, fallback: str) -> str:
    if isinstance(value, dict):
        return str(value.get("simpleText") or value.get("text") or fallback).strip() or fallback
    return str(value or fallback).strip() or fallback


_KNOWN_LANGUAGE_NAMES = {
    "ar": "Arabic",
    "de": "German",
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "hi": "Hindi",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "nl": "Dutch",
    "pt": "Portuguese",
    "ru": "Russian",
    "tr": "Turkish",
    "ur": "Urdu",
    "zh": "Chinese",
}


def _language_info(code: str, name: Any = None, *, original: bool = False, asr: bool = False) -> dict[str, Any]:
    normalized = str(code or "").strip()
    base_code = normalized.lower().split("-", 1)[0]
    display_name = _language_name(name, normalized or "Unknown language")
    if base_code in _KNOWN_LANGUAGE_NAMES and (not name or display_name.lower() == normalized.lower()):
        display_name = _KNOWN_LANGUAGE_NAMES[base_code]
    return {
        "code": normalized,
        "name": display_name,
        "isOriginal": original,
        "isAutoGenerated": asr,
    }


def _languages_from_tracks(
    tracks: list[dict[str, Any]],
    translations: list[dict[str, Any]] | None = None,
    original_code: str = "",
) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    seen: set[str] = set()
    for track in tracks:
        code = str(track.get("languageCode") or track.get("lang_code") or "").strip()
        if not code or code in seen:
            continue
        seen.add(code)
        result.append(_language_info(
            code,
            track.get("name") or track.get("languageName"),
            original=code == original_code,
            asr=str(track.get("kind", "")).lower() == "asr",
        ))
    for translation in translations or []:
        code = str(translation.get("languageCode") or translation.get("code") or "").strip()
        if not code or code in seen:
            continue
        seen.add(code)
        result.append(_language_info(code, translation.get("languageName") or translation.get("name")))
    return result


def _default_audio_language(player_data: dict[str, Any]) -> str:
    details = player_data.get("videoDetails", {})
    if not isinstance(details, dict):
        return ""
    return str(details.get("defaultAudioLanguage") or details.get("defaultAudioLanguageCode") or "").strip()


def _prioritize_original_track(tracks: list[dict[str, Any]], language_code: str) -> list[dict[str, Any]]:
    preferred = str(language_code or "").strip().lower()
    if not preferred:
        return tracks
    preferred_base = preferred.split("-", 1)[0]
    index = next((i for i, track in enumerate(tracks) if str(track.get("languageCode", "")).strip().lower() == preferred), None)
    if index is None:
        index = next((i for i, track in enumerate(tracks) if str(track.get("languageCode", "")).strip().lower().split("-", 1)[0] == preferred_base), None)
    if index is None:
        return tracks
    return [tracks[index], *tracks[:index], *tracks[index + 1:]]


def _discover_default_audio_language(video_id: str, session: requests.Session) -> str:
    """Read YouTube's audio-language hint without changing the caption fallback stack."""
    token_details = _po_token_details(video_id)
    for config in _innertube_client_configs(token_details):
        try:
            response = _youtube_request(
                session,
                "POST",
                "https://www.youtube.com/youtubei/v1/player?prettyPrint=false",
                headers=config["headers"],
                json={"context": {"client": config["client"]}, "videoId": video_id},
                timeout=10,
            )
            if response.status_code == 429:
                continue
            if response.status_code < 400:
                language = _default_audio_language(response.json())
                if language:
                    return language
        except (requests.RequestException, ValueError, TypeError):
            continue
    return ""


def _result(
    segments: list[dict[str, Any]],
    tracks: list[dict[str, Any]],
    original_track: dict[str, Any],
    selected_track: dict[str, Any],
    translations: list[dict[str, Any]] | None = None,
) -> TranscriptResult:
    original_code = str(original_track.get("languageCode") or original_track.get("lang_code") or "").strip()
    return {
        "segments": segments,
        "originalLanguage": _language_info(
            original_code,
            original_track.get("name"),
            original=True,
            asr=str(original_track.get("kind", "")).lower() == "asr",
        ),
    }


def extract_video_id(url_or_id: str) -> str:
    """Extract an 11-character YouTube video ID from a URL or raw ID."""
    value = url_or_id.strip()
    pattern = r"(?:v=|/([0-9A-Za-z_-]{11}).*|youtu[.]be/|embed/|shorts/)([0-9A-Za-z_-]{11})"
    match = re.search(pattern, value)
    if match:
        return match.group(1) or match.group(2)
    if len(value) == 11 and re.match(r"^[0-9A-Za-z_-]{11}$", value):
        return value
    raise ValueError("Invalid YouTube URL or Video ID")


def _proxy_mapping() -> dict[str, str] | None:
    """Return the local WARP HTTP proxy for both HTTP and HTTPS requests."""
    warp_proxy = os.getenv("WARP_HTTP_PROXY", "").strip()
    if os.getenv("WARP_ENABLED", "").strip().lower() == "true" and not warp_proxy:
        warp_proxy = "http://127.0.0.1:9091"
    if warp_proxy:
        return {"http": warp_proxy, "https": warp_proxy}

    # Cloudflare Worker requests are wrapped explicitly by _youtube_request;
    # they are not HTTP CONNECT proxies and must not be passed to requests'
    # session.proxies mapping.
    return None


def _youtube_cookie_file() -> str | None:
    """Return an optional Netscape-format YouTube cookie file."""
    cookie_file = os.getenv("YOUTUBE_COOKIES_FILE", "").strip()
    return cookie_file if cookie_file and os.path.isfile(cookie_file) else None


def _po_token_details(video_id: str) -> dict[str, str] | None:
    """Ask the local sidecar for a content-bound PO-token when enabled."""
    if os.getenv("PO_TOKEN_ENABLED", "").strip().lower() != "true":
        return None
    sidecar_url = os.getenv("PO_TOKEN_SIDECAR_URL", "http://127.0.0.1:4416").strip().rstrip("/")
    try:
        with requests.Session() as session:
            session.trust_env = False
            response = session.get(
                f"{sidecar_url}/token",
                params={"videoId": video_id},
                timeout=float(os.getenv("PO_TOKEN_REQUEST_TIMEOUT_SECONDS", "12")),
            )
            response.raise_for_status()
            data = response.json()
        visitor_data = str(data.get("visitorData", "")).strip()
        po_token = str(data.get("poToken", "")).strip()
        if not visitor_data or len(po_token) < 100:
            return None
        return {"visitorData": visitor_data, "poToken": po_token}
    except (requests.RequestException, ValueError, TypeError):
        # PO tokens are an optional enhancement. Keep the WARP and library
        # extraction paths available when YouTube or the sidecar changes.
        return None


def _caption_url_with_po_token(caption_url: str, token_details: dict[str, str] | None) -> str:
    """Add the parameters used by YouTube's browser subtitle requests."""
    if not token_details:
        return caption_url
    parts = urlsplit(caption_url)
    query = dict(parse_qsl(parts.query, keep_blank_values=True))
    query.update(
        {
            "potc": "1",
            "pot": token_details["poToken"],
            "c": "WEB",
            "cver": "2.20240301.00.00",
        }
    )
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment))


def _caption_url_with_format(caption_url: str, format_name: str | None) -> str:
    """Set or remove timedtext fmt while preserving the signed query parameters."""
    parts = urlsplit(caption_url)
    query = [(key, value) for key, value in parse_qsl(parts.query, keep_blank_values=True) if key != "fmt"]
    if format_name:
        query.append(("fmt", format_name))
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment))


def _youtube_session() -> requests.Session:
    """Build a YouTube HTTP session with browser headers and optional cookies."""
    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": YOUTUBE_USER_AGENT,
            "Accept-Language": "en-US,en;q=0.9",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Cookie": YOUTUBE_CONSENT_COOKIE,
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
            "Upgrade-Insecure-Requests": "1",
        }
    )
    proxies = _proxy_mapping()
    if proxies:
        session.proxies.update(proxies)
    cookie_file = _youtube_cookie_file()
    if cookie_file:
        try:
            jar = MozillaCookieJar(cookie_file)
            jar.load(ignore_discard=True, ignore_expires=True)
            session.cookies.update(jar)
        except Exception:
            # A malformed optional cookie file must not prevent public-track
            # extraction from being attempted.
            pass
    return session


def _worker_proxy_url() -> str:
    """Read the current and legacy names for the Worker relay endpoint."""
    return os.getenv("CF_WORKER_PROXY", "").strip() or os.getenv("CF_WORKER_PROXY_URL", "").strip()


def _worker_target_url(target_url: str) -> str:
    """Wrap a YouTube URL in the configured Cloudflare Worker endpoint."""
    worker_url = _worker_proxy_url()
    if not worker_url:
        return target_url
    if worker_url.endswith("?url="):
        worker_url = worker_url[:-5]
    elif worker_url.endswith("&url="):
        worker_url = worker_url[:-5]
    parts = urlsplit(worker_url)
    query = dict(parse_qsl(parts.query, keep_blank_values=True))
    query["url"] = target_url
    return urlunsplit((parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment))


def _youtube_request(session: requests.Session, method: str, target_url: str, **kwargs: Any) -> requests.Response:
    """Send a YouTube request with a small, bounded 429 retry window."""
    worker_url = _worker_proxy_url()
    headers = dict(kwargs.pop("headers", {}) or {})
    if worker_url:
        auth_token = os.getenv("CF_WORKER_AUTH_TOKEN", "").strip()
        if auth_token:
            headers["x-proxy-auth"] = auth_token
        request_url = _worker_target_url(target_url)
    else:
        request_url = target_url
    kwargs["headers"] = headers

    try:
        max_retries = max(0, min(2, int(os.getenv("YOUTUBE_429_RETRIES", "2"))))
    except ValueError:
        max_retries = 2
    for attempt in range(max_retries + 1):
        response = session.request(method, request_url, **kwargs)
        if response.status_code != 429 or attempt >= max_retries:
            return response
        retry_after = response.headers.get("Retry-After", "")
        try:
            server_delay = float(retry_after)
        except ValueError:
            server_delay = 0.0
        exponential_delay = min(8.0, 0.75 * (2 ** attempt))
        delay = max(exponential_delay, server_delay) + random.uniform(0, 0.35)
        time.sleep(delay)
    return response


def _parse_player_response(page: str) -> dict[str, Any]:
    """Decode the embedded ytInitialPlayerResponse JSON object."""
    decoder = json.JSONDecoder()
    markers = (
        "ytInitialPlayerResponse = ",
        "var ytInitialPlayerResponse = ",
    )
    for marker in markers:
        start = page.find(marker)
        if start < 0:
            continue
        payload = page[start + len(marker) :]
        try:
            parsed, _ = decoder.raw_decode(payload)
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict):
            return parsed
    raise RuntimeError("Unable to parse video player data from YouTube.")


def _extract_innertube_api_key(page: str) -> str:
    """Extract the current public InnerTube key from a watch page."""
    match = re.search(r'"INNERTUBE_API_KEY"\s*:\s*"([^"]+)"', page)
    if not match:
        raise RuntimeError("Unable to extract YouTube InnerTube API key.")
    return match.group(1)


def _caption_tracks_from_markup(page: str) -> list[dict[str, Any]]:
    """Extract captionTracks directly when YouTube omits a parseable player marker."""
    marker = '"captionTracks"'
    marker_index = page.find(marker)
    if marker_index < 0:
        return []
    list_start = page.find("[", marker_index + len(marker))
    if list_start < 0:
        return []
    tracks: list[dict[str, Any]] = []
    try:
        parsed, _ = json.JSONDecoder().raw_decode(page[list_start:])
        if isinstance(parsed, list):
            tracks = [track for track in parsed if isinstance(track, dict)]
    except json.JSONDecodeError:
        pass
    if tracks:
        return tracks

    # Last-resort extraction for pages where nested JSON is escaped or truncated.
    for match in re.finditer(r'"baseUrl"\s*:\s*"(https://www[.]youtube[.]com/api/timedtext[^" ]+)"', page):
        try:
            base_url = json.loads(f'"{match.group(1)}"')
        except json.JSONDecodeError:
            continue
        if base_url:
            tracks.append({"baseUrl": base_url})
    return tracks


def _caption_tracks(player_data: dict[str, Any]) -> list[dict[str, Any]]:
    captions = player_data.get("captions", {})
    renderer = captions.get("playerCaptionsTracklistRenderer", {}) if isinstance(captions, dict) else {}
    tracks = renderer.get("captionTracks", []) if isinstance(renderer, dict) else []
    return [track for track in tracks if isinstance(track, dict)]


def _discover_caption_catalog(video_id: str) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Discover source tracks and YouTube's translation catalog without fetching text."""
    session = _youtube_session()
    timedtext_tracks: list[dict[str, Any]] = []
    try:
        list_url = f"https://www.youtube.com/api/timedtext?type=list&v={video_id}"
        try:
            response = _youtube_request(
                session,
                "GET",
                list_url,
                headers={"Accept": "application/xml,text/xml,application/json,*/*"},
                timeout=10,
            )
            if response.status_code == 429:
                raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
            if response.ok:
                timedtext_tracks = _parse_timedtext_track_list(response.text)
        except YouTubeRateLimitError:
            raise
        except requests.RequestException:
            timedtext_tracks = []

        token_details = _po_token_details(video_id)
        for config in _innertube_client_configs(token_details):
            try:
                response = _youtube_request(
                    session,
                    "POST",
                    "https://www.youtube.com/youtubei/v1/player?prettyPrint=false",
                    headers=config["headers"],
                    json={"context": {"client": config["client"]}, "videoId": video_id},
                    timeout=10,
                )
                if response.status_code == 429:
                    raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
                if not response.ok:
                    continue
                player_data = response.json()
                tracks = _caption_tracks(player_data)
                if tracks:
                    return _prioritize_original_track(tracks, _default_audio_language(player_data)), []
            except YouTubeRateLimitError:
                raise
            except (requests.RequestException, ValueError):
                continue
        if timedtext_tracks:
            return timedtext_tracks, []
        raise NoCaptionsError("No public captions are available for this video.")
    finally:
        session.close()


def _ordered_caption_tracks(tracks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Prefer English, then ASR, then any remaining usable caption track."""
    usable = [track for track in tracks if str(track.get("baseUrl", "")).strip()]

    def rank(track: dict[str, Any]) -> tuple[int, int]:
        language = str(track.get("languageCode", "")).lower()
        is_english = language in {"en", "en-us", "en-gb"} or language.startswith("en-")
        is_asr = str(track.get("kind", "")).lower() == "asr"
        if is_english and not is_asr:
            return (0, 0)
        if is_english:
            return (1, 0)
        if is_asr:
            return (2, 0)
        return (3, 0)

    return [
        track
        for _, track in sorted(enumerate(usable), key=lambda item: (rank(item[1]), item[0]))
    ]


def _select_caption_track(tracks: list[dict[str, Any]]) -> dict[str, Any]:
    ordered = _ordered_caption_tracks(tracks)
    if not ordered:
        raise NoCaptionsError("No public captions are available for this video.")
    return ordered[0]


def _select_original_caption_track(tracks: list[dict[str, Any]], preferred_language: str | None = None) -> dict[str, Any]:
    usable = [track for track in tracks if str(track.get("baseUrl", "")).strip()]
    if not usable:
        raise NoCaptionsError("No public captions are available for this video.")
    preferred = str(preferred_language or "").strip().lower()
    if preferred:
        preferred_base = preferred.split("-", 1)[0]
        original = next((track for track in usable if str(track.get("languageCode", "")).strip().lower() == preferred), None)
        original = original or next((track for track in usable if str(track.get("languageCode", "")).strip().lower().split("-", 1)[0] == preferred_base), None)
        if original:
            return original
    return usable[0]


def _parse_timedtext_track_list(payload: str) -> list[dict[str, Any]]:
    """Parse the public timedtext track list without assuming a player JSON payload."""
    text = payload.strip()
    if not text:
        return []
    try:
        root = ET.fromstring(text)
    except ET.ParseError:
        return []
    tracks: list[dict[str, Any]] = []
    for node in root.iter("track"):
        language = str(node.attrib.get("lang_code", "")).strip()
        if not language:
            continue
        track: dict[str, Any] = {
            "languageCode": language,
            "baseUrl": "https://www.youtube.com/api/timedtext",
        }
        for source_key, target_key in (("kind", "kind"), ("name", "name"), ("tlang", "tlang")):
            value = str(node.attrib.get(source_key, "")).strip()
            if value:
                track[target_key] = value
        tracks.append(track)
    return tracks


def _fetch_timedtext_direct_result(video_id: str) -> TranscriptResult:
    """Fetch timedtext captions and retain the source language catalog."""
    session = _youtube_session()
    try:
        list_url = f"https://www.youtube.com/api/timedtext?type=list&v={video_id}"
        response = _youtube_request(
            session,
            "GET",
            list_url,
            headers={"Accept": "application/xml,text/xml,application/json,*/*"},
            timeout=20,
        )
        if response.status_code == 429:
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
        response.raise_for_status()
        tracks = _parse_timedtext_track_list(response.text)
        if not tracks:
            raise NoCaptionsError("No public captions are available for this video.")

        for track in tracks:
            language = str(track["languageCode"])
            query: list[tuple[str, str]] = [("v", video_id), ("lang", language)]
            for key in ("kind", "name", "tlang"):
                value = str(track.get(key, "")).strip()
                if value:
                    query.append((key, value))
            track["baseUrl"] = urlunsplit(("https", "www.youtube.com", "/api/timedtext", urlencode(query), ""))

        if len(tracks) > 1:
            tracks = _prioritize_original_track(tracks, _discover_default_audio_language(video_id, session))
        original_track = _select_original_caption_track(tracks)
        selected_track = original_track
        segments = _fetch_caption_track(session, selected_track, _po_token_details(video_id))
        return _result(segments, tracks, original_track, selected_track, [])
    finally:
        session.close()


def _fetch_timedtext_direct(video_id: str) -> list[dict[str, Any]]:
    """Try YouTube's lightweight timedtext list endpoint before InnerTube."""
    return _fetch_timedtext_direct_result(video_id)["segments"]


def _parse_caption_payload(payload: str) -> list[dict[str, Any]]:
    """Parse timedtext XML or json3 into the common segment shape."""
    text = payload.strip()
    if not text:
        raise CaptionPayloadError("YouTube returned an empty caption payload.")

    try:
        root = ET.fromstring(text)
        segments: list[dict[str, Any]] = []
        for node in root.iter("text"):
            value = html_lib.unescape(node.text or "").replace("\n", " ").strip()
            if not value:
                continue
            segments.append(
                {
                    "text": value,
                    "start": max(0, float(node.attrib.get("start", 0) or 0)),
                    "duration": max(0, float(node.attrib.get("dur", 0) or 0)),
                }
            )
        if segments:
            return segments
    except (ET.ParseError, ValueError):
        pass

    try:
        data = json.loads(text)
        segments = []
        for event in data.get("events", []):
            start = max(0, float(event.get("tStartMs", 0) or 0) / 1000)
            duration = max(0, float(event.get("dDurationMs", 0) or 0) / 1000)
            value = "".join(str(part.get("utf8", "")) for part in event.get("segs", []))
            value = html_lib.unescape(value).replace("\n", " ").strip()
            if value:
                segments.append({"text": value, "start": start, "duration": duration})
        if segments:
            return segments
    except (json.JSONDecodeError, TypeError, ValueError):
        pass

    # yt-dlp commonly exposes WebVTT when json3 is unavailable.
    segments = []
    cue_pattern = re.compile(
        r"(?m)^(?P<start>\d{2}:\d{2}(?::\d{2})?[.,]\d{3})\s+-->\s+(?P<end>\d{2}:\d{2}(?::\d{2})?[.,]\d{3})\s*$"
    )
    cues = list(cue_pattern.finditer(text))

    def parse_vtt_time(value: str) -> float:
        parts = value.replace(",", ".").split(":")
        if len(parts) == 2:
            minutes, seconds = parts
            return float(minutes) * 60 + float(seconds)
        hours, minutes, seconds = parts
        return float(hours) * 3600 + float(minutes) * 60 + float(seconds)

    for index, cue in enumerate(cues):
        body_start = cue.end()
        body_end = cues[index + 1].start() if index + 1 < len(cues) else len(text)
        value = re.sub(r"<[^>]+>", "", text[body_start:body_end]).strip()
        value = html_lib.unescape(re.sub(r"\s+", " ", value))
        if value:
            start = parse_vtt_time(cue.group("start"))
            end = parse_vtt_time(cue.group("end"))
            segments.append({"text": value, "start": start, "duration": max(0, end - start)})
    if segments:
        return segments

    raise CaptionPayloadError("YouTube returned an empty or corrupted transcript response.")


def _fetch_caption_track(
    session: requests.Session,
    track: dict[str, Any],
    token_details: dict[str, str] | None,
) -> list[dict[str, Any]]:
    """Fetch one track as JSON3 first and as raw XML when JSON3 is unusable."""
    base_url = str(track.get("baseUrl", "")).strip()
    if not base_url:
        raise CaptionPayloadError("Caption track found but lacks a valid download URL.")

    signed_url = _caption_url_with_po_token(base_url, token_details)
    json3_url = _caption_url_with_format(signed_url, "json3")
    json3_error: Exception | None = None
    try:
        response = _youtube_request(session, "GET", json3_url, timeout=20)
        if response.status_code == 429:
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
        response.raise_for_status()
        return _parse_caption_payload(response.text)
    except YouTubeRateLimitError:
        raise
    except (requests.RequestException, CaptionPayloadError) as error:
        json3_error = error

    # Some signed timedtext URLs ignore fmt=json3 or return an empty body. The
    # same URL without fmt asks YouTube for the classic XML transcript format.
    xml_url = _caption_url_with_format(signed_url, None)
    try:
        response = _youtube_request(session, "GET", xml_url, timeout=20)
        if response.status_code == 429:
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
        response.raise_for_status()
        return _parse_caption_payload(response.text)
    except YouTubeRateLimitError:
        raise
    except (requests.RequestException, CaptionPayloadError) as error:
        raise CaptionPayloadError("YouTube returned no usable caption text.") from (json3_error or error)


def _innertube_client_configs(token_details: dict[str, str] | None) -> list[dict[str, Any]]:
    """Return stable WEB and Android player contexts for compatibility fallback."""
    web_client: dict[str, Any] = {
        "hl": "en",
        "gl": "US",
        "clientName": "WEB",
        "clientVersion": "2.20240301.00.00",
    }
    if token_details:
        web_client.update(
            {
                "visitorData": token_details["visitorData"],
                "poToken": token_details["poToken"],
            }
        )
    return [
        {"client": web_client, "headers": {}},
        {
            "client": {
                "hl": "en",
                "gl": "US",
                "clientName": "ANDROID",
                "clientVersion": "19.09.37",
                "androidSdkVersion": 30,
            },
            "headers": {
                "User-Agent": "com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip",
                "Accept": "application/json",
            },
        },
    ]


def _fetch_innertube_transcript(video_id: str) -> list[dict[str, Any]]:
    """Fetch player captionTracks using WEB then Android and parse each track."""
    innertube_url = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false"
    token_details = _po_token_details(video_id)
    session = _youtube_session()
    saw_successful_player = False
    saw_no_tracks = False
    last_error: Exception | None = None
    try:
        for config in _innertube_client_configs(token_details):
            payload = {
                "context": {"client": config["client"]},
                "videoId": video_id,
            }
            try:
                response = _youtube_request(
                    session,
                    "POST",
                    innertube_url,
                    headers=config["headers"],
                    json=payload,
                    timeout=20,
                )
                if response.status_code == 429:
                    raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
                response.raise_for_status()
                player_data = response.json()
                saw_successful_player = True
            except YouTubeRateLimitError:
                raise
            except (requests.RequestException, ValueError) as error:
                last_error = error
                continue

            playability = player_data.get("playabilityStatus", {}).get("status")
            if playability in {"UNPLAYABLE", "LOGIN_REQUIRED"}:
                raise RuntimeError("The requested video is unavailable or private.")

            tracks = _caption_tracks(player_data)
            if not tracks:
                saw_no_tracks = True
                continue
            preferred_language = _default_audio_language(player_data)
            ordered_tracks = _prioritize_original_track(tracks, preferred_language)
            for track in [ordered_tracks[0], *_ordered_caption_tracks(ordered_tracks[1:])]:
                try:
                    return _fetch_caption_track(session, track, token_details)
                except YouTubeRateLimitError:
                    raise
                except (requests.RequestException, CaptionPayloadError) as error:
                    last_error = error
                    continue

        if saw_no_tracks and saw_successful_player:
            raise NoCaptionsError("No public captions are available for this video.")
        if last_error:
            raise CaptionPayloadError("YouTube returned no usable caption text.") from last_error
        raise RuntimeError("InnerTube did not return usable player data.")
    finally:
        session.close()


def _fetch_innertube_api_key_result(video_id: str) -> TranscriptResult:
    """Use a watch-page API key and Android player context as a final fallback.

    This path is reached only after the primary catalog and InnerTube clients
    fail. It still uses the Worker/WARP wrapper, original-language ordering,
    and the common JSON3/XML caption parser.
    """
    watch_url = f"https://www.youtube.com/watch?v={video_id}"
    session = _youtube_session()
    try:
        response = _youtube_request(session, "GET", watch_url, timeout=20)
        if response.status_code == 429:
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
        response.raise_for_status()
        api_key = _extract_innertube_api_key(response.text)

        player_url = f"https://www.youtube.com/youtubei/v1/player?key={api_key}&prettyPrint=false"
        player_response = _youtube_request(
            session,
            "POST",
            player_url,
            headers={
                "Content-Type": "application/json",
                "Accept": "application/json",
                "User-Agent": "com.google.android.youtube/20.10.38 (Linux; U; Android 11)",
            },
            json={
                "context": {
                    "client": {
                        "clientName": "ANDROID",
                        "clientVersion": "20.10.38",
                        "androidSdkVersion": 30,
                        "hl": "en",
                        "gl": "US",
                    }
                },
                "videoId": video_id,
                "params": "CgIQBg==",
                "playbackContext": {
                    "contentPlaybackContext": {"html5Preference": "HTML5_PREF_WANTS"}
                },
            },
            timeout=20,
        )
        if player_response.status_code == 429:
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
        player_response.raise_for_status()
        player_data = player_response.json()
        playability = player_data.get("playabilityStatus", {}).get("status")
        if playability in {"UNPLAYABLE", "LOGIN_REQUIRED"}:
            raise RuntimeError("The requested video is unavailable or private.")

        tracks = _caption_tracks(player_data)
        if not tracks:
            raise NoCaptionsError("No public captions are available for this video.")
        token_details = _po_token_details(video_id)
        ordered_tracks = _prioritize_original_track(tracks, _default_audio_language(player_data))
        last_error: Exception | None = None
        for track in [ordered_tracks[0], *_ordered_caption_tracks(ordered_tracks[1:])]:
            try:
                segments = _fetch_caption_track(session, track, token_details)
                return _result(segments, tracks, ordered_tracks[0], track, [])
            except YouTubeRateLimitError:
                raise
            except (requests.RequestException, CaptionPayloadError) as error:
                last_error = error
        raise CaptionPayloadError("YouTube returned no usable caption text.") from last_error
    finally:
        session.close()


def _fetch_direct_transcript(video_id: str) -> list[dict[str, Any]]:
    """Fetch signed caption tracks from the watch page with JSON3/XML fallback."""
    watch_url = f"https://www.youtube.com/watch?v={video_id}"
    with _youtube_session() as session:
        try:
            response = _youtube_request(session, "GET", watch_url, timeout=20)
            if response.status_code == 429:
                raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
            response.raise_for_status()
        except YouTubeRateLimitError:
            raise
        except requests.RequestException as error:
            raise RuntimeError(f"Failed to reach YouTube page: {error}") from error

        try:
            player_data = _parse_player_response(response.text)
        except RuntimeError:
            markup_tracks = _caption_tracks_from_markup(response.text)
            if not markup_tracks:
                raise
            player_data = {"captions": {"playerCaptionsTracklistRenderer": {"captionTracks": markup_tracks}}}
        playability = player_data.get("playabilityStatus", {}).get("status")
        if playability in {"UNPLAYABLE", "LOGIN_REQUIRED"}:
            raise RuntimeError("The requested video is unavailable or private.")

        tracks = _caption_tracks(player_data)
        if not tracks:
            tracks = _caption_tracks_from_markup(response.text)
        if not tracks:
            raise NoCaptionsError("No public captions are available for this video.")
        token_details = _po_token_details(video_id)
        last_error: Exception | None = None
        ordered_tracks = _prioritize_original_track(tracks, _default_audio_language(player_data))
        for track in [ordered_tracks[0], *_ordered_caption_tracks(ordered_tracks[1:])]:
            try:
                return _fetch_caption_track(session, track, token_details)
            except YouTubeRateLimitError:
                raise
            except (requests.RequestException, CaptionPayloadError) as error:
                last_error = error
        raise CaptionPayloadError("YouTube returned no usable caption text.") from last_error


def _fetch_ytdlp_transcript_result(video_id: str) -> TranscriptResult:
    """Use yt-dlp metadata while preserving source and available caption languages."""
    if yt_dlp is None:
        raise YtDlpUnavailableError("yt-dlp is not installed.")
    options: dict[str, Any] = {
        "skip_download": True,
        "writesubtitles": True,
        "writeautomaticsub": True,
        "subtitleslangs": ["all"],
        "quiet": True,
        "no_warnings": True,
        "ignoreconfig": True,
        "http_headers": {
            "User-Agent": YOUTUBE_USER_AGENT,
            "Accept-Language": "en-US,en;q=0.9",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        },
    }
    warp_proxy = os.getenv("WARP_HTTP_PROXY", "").strip()
    if warp_proxy:
        options["proxy"] = warp_proxy
    try:
        with yt_dlp.YoutubeDL(options) as ydl:
            info = ydl.extract_info(f"https://www.youtube.com/watch?v={video_id}", download=False)
    except Exception as error:
        message = str(error).lower()
        if any(token in message for token in ("429", "too many requests", "sign in to confirm", "not a bot", "rate limit")):
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.") from error
        raise RuntimeError("yt-dlp could not retrieve YouTube caption metadata.") from error

    manual = info.get("subtitles") or {}
    automatic = info.get("automatic_captions") or {}
    catalog: list[tuple[str, bool, list[dict[str, Any]]]] = []
    for language, formats in manual.items():
        if isinstance(formats, list):
            catalog.append((str(language), False, [item for item in formats if isinstance(item, dict)]))
    for language, formats in automatic.items():
        if isinstance(formats, list):
            catalog.append((str(language), True, [item for item in formats if isinstance(item, dict)]))
    catalog = [item for item in catalog if any(str(fmt.get("url", "")).strip() for fmt in item[2])]
    if not catalog:
        raise NoCaptionsError("No public captions are available for this video.")

    preferred_language = str(info.get("language") or info.get("original_language") or "").strip().lower()
    if preferred_language:
        preferred_base = preferred_language.split("-", 1)[0]
        preferred_index = next((index for index, item in enumerate(catalog) if item[0].lower() == preferred_language or item[0].lower().split("-", 1)[0] == preferred_base), None)
        if preferred_index is not None:
            catalog = [catalog[preferred_index], *catalog[:preferred_index], *catalog[preferred_index + 1:]]
    original_language, original_asr, original_formats = catalog[0]
    selected_language = original_language
    selected_asr = original_asr
    selected_formats = original_formats
    if not selected_formats:
        raise CaptionPayloadError("YouTube returned no usable caption text.")

    available_tracks = [
        {"languageCode": language, "name": language, "kind": "asr" if is_asr else "", "baseUrl": str(formats[0].get("url", ""))}
        for language, is_asr, formats in catalog
    ]
    original_track = available_tracks[0]
    selected_track = {"languageCode": selected_language, "name": selected_language, "kind": "asr" if selected_asr else "", "baseUrl": str(selected_formats[0].get("url", ""))}
    session = _youtube_session()
    try:
        last_error: Exception | None = None
        ordered_formats = sorted(selected_formats, key=lambda item: {"json3": 0, "vtt": 1, "srv3": 2, "xml": 3}.get(str(item.get("ext", "")).lower(), 4))
        for subtitle_format in ordered_formats:
            try:
                response = _youtube_request(session, "GET", str(subtitle_format["url"]), timeout=20)
                if response.status_code == 429:
                    raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
                if response.ok:
                    segments = _parse_caption_payload(response.text)
                    return _result(segments, available_tracks, original_track, selected_track, [])
            except YouTubeRateLimitError:
                raise
            except (requests.RequestException, CaptionPayloadError) as error:
                last_error = error
        raise CaptionPayloadError("YouTube returned no usable caption text.") from last_error
    finally:
        session.close()


def _fetch_ytdlp_transcript(video_id: str) -> list[dict[str, Any]]:
    """Use yt-dlp's maintained YouTube extractor as an optional final fallback."""
    if yt_dlp is None:
        raise YtDlpUnavailableError("yt-dlp is not installed.")

    options: dict[str, Any] = {
        "skip_download": True,
        "writesubtitles": True,
        "writeautomaticsub": True,
        "subtitleslangs": ["en", "en-US", "en-GB"],
        "quiet": True,
        "no_warnings": True,
        "ignoreconfig": True,
        "http_headers": {
            "User-Agent": YOUTUBE_USER_AGENT,
            "Accept-Language": "en-US,en;q=0.9",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        },
    }
    warp_proxy = os.getenv("WARP_HTTP_PROXY", "").strip()
    if warp_proxy:
        options["proxy"] = warp_proxy

    try:
        with yt_dlp.YoutubeDL(options) as ydl:
            info = ydl.extract_info(f"https://www.youtube.com/watch?v={video_id}", download=False)
    except Exception as error:
        message = str(error)
        lowered = message.lower()
        if any(token in lowered for token in ("429", "too many requests", "sign in to confirm", "not a bot", "rate limit")):
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.") from error
        raise RuntimeError("yt-dlp could not retrieve YouTube caption metadata.") from error

    manual = info.get("subtitles") or {}
    automatic = info.get("automatic_captions") or {}
    tracks: list[tuple[str, bool, list[dict[str, Any]]]] = []
    for language, formats in manual.items():
        if isinstance(formats, list):
            tracks.append((str(language), False, [item for item in formats if isinstance(item, dict)]))
    for language, formats in automatic.items():
        if isinstance(formats, list):
            tracks.append((str(language), True, [item for item in formats if isinstance(item, dict)]))
    if not tracks:
        raise NoCaptionsError("No public captions are available for this video.")

    preferred_language = str(info.get("language") or info.get("original_language") or "").strip().lower()
    if preferred_language:
        preferred_base = preferred_language.split("-", 1)[0]
        preferred_index = next(
            (
                index
                for index, item in enumerate(tracks)
                if item[0].lower() == preferred_language
                or item[0].lower().split("-", 1)[0] == preferred_base
            ),
            None,
        )
        if preferred_index is not None:
            tracks = [tracks[preferred_index], *tracks[:preferred_index], *tracks[preferred_index + 1:]]

    session = _youtube_session()
    try:
        for _language, _is_asr, formats in tracks:
            ordered_formats = sorted(
                (item for item in formats if str(item.get("url", "")).strip()),
                key=lambda item: {"json3": 0, "vtt": 1, "srv3": 2, "xml": 3}.get(str(item.get("ext", "")).lower(), 4),
            )
            for subtitle_format in ordered_formats:
                subtitle_url = str(subtitle_format["url"])
                response = _youtube_request(session, "GET", subtitle_url, timeout=20)
                if response.status_code == 429:
                    raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.")
                if not response.ok:
                    continue
                try:
                    return _parse_caption_payload(response.text)
                except CaptionPayloadError:
                    continue
    finally:
        session.close()
    raise CaptionPayloadError("YouTube returned no usable caption text.")


def _normalize_library_segments(fetched: Any) -> list[dict[str, Any]]:
    if not fetched:
        raise RuntimeError("YouTube returned an empty transcript response.")
    normalized: list[dict[str, Any]] = []
    for item in fetched:
        if isinstance(item, dict):
            text = item.get("text", "")
            start = item.get("start", 0)
            duration = item.get("duration", 0)
        else:
            text = getattr(item, "text", "")
            start = getattr(item, "start", 0)
            duration = getattr(item, "duration", 0)
        normalized.append({
            "text": str(text).strip(),
            "start": float(start or 0),
            "duration": float(duration or 0),
        })
    return [item for item in normalized if item["text"]]


def _youtube_transcript_api_fetch_result(video_id: str) -> TranscriptResult:
    """Use youtube-transcript-api as an original-language compatibility fallback."""
    kwargs: dict[str, Any] = {}
    proxies = _proxy_mapping()
    if proxies:
        kwargs["proxies"] = proxies
    cookie_file = _youtube_cookie_file()
    if cookie_file:
        kwargs["cookies"] = cookie_file

    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id, **kwargs)
    tracks = list(transcript_list)
    if not tracks:
        raise RuntimeError("No transcript found in any language for this video.")
    original = tracks[0]
    fetched = original.fetch()
    segments = _normalize_library_segments(fetched)
    original_code = str(getattr(original, "language_code", "")).strip()
    original_track = {
        "languageCode": original_code,
        "name": getattr(original, "language", None),
        "kind": "asr" if bool(getattr(original, "is_generated", False)) else "",
    }
    return _result(segments, [], original_track, original_track, [])


def _youtube_transcript_api_fetch(video_id: str) -> list[dict[str, Any]]:
    """Fetch tracks through youtube-transcript-api as a compatibility fallback."""
    kwargs: dict[str, Any] = {}
    proxies = _proxy_mapping()
    if proxies:
        kwargs["proxies"] = proxies
    cookie_file = _youtube_cookie_file()
    if cookie_file:
        kwargs["cookies"] = cookie_file

    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id, **kwargs)
    tracks = list(transcript_list)
    if not tracks:
        raise RuntimeError("No transcript found in any language for this video.")
    transcript = tracks[0]
    fetched = transcript.fetch()
    if not fetched:
        raise RuntimeError("YouTube returned an empty transcript response.")
    normalized: list[dict[str, Any]] = []
    for item in fetched:
        if isinstance(item, dict):
            text = item.get("text", "")
            start = item.get("start", 0)
            duration = item.get("duration", 0)
        else:
            text = getattr(item, "text", "")
            start = getattr(item, "start", 0)
            duration = getattr(item, "duration", 0)
        normalized.append({
            "text": str(text).strip(),
            "start": float(start or 0),
            "duration": float(duration or 0),
        })
    return normalized


def _fetch_transcript_in_language(video_id: str) -> TranscriptResult:
    """Fetch only the caption track matching the video's original audio language."""
    try:
        return _fetch_timedtext_direct_result(video_id)
    except (RuntimeError, requests.RequestException):
        # The direct list is the fastest path. If it is blocked, use the
        # InnerTube catalog before handing control to the legacy stack.
        tracks, _translations = _discover_caption_catalog(video_id)
        original_track = _select_original_caption_track(tracks)
        session = _youtube_session()
        try:
            segments = _fetch_caption_track(session, original_track, _po_token_details(video_id))
        finally:
            session.close()
        return _result(segments, tracks, original_track, original_track, [])


def _fetch_transcript_result(video_id: str) -> TranscriptResult:
    """Use the original-language catalog first, retaining the complete fallback stack."""
    try:
        return _fetch_transcript_in_language(video_id)
    except (RuntimeError, requests.RequestException) as catalog_error:
        try:
            return _youtube_transcript_api_fetch_result(video_id)
        except Exception:
            pass
        try:
            return _fetch_innertube_api_key_result(video_id)
        except Exception:
            pass
        try:
            return _fetch_ytdlp_transcript_result(video_id)
        except Exception:
            pass
        try:
            segments = _fetch_transcript(video_id)
        except Exception:
            if isinstance(catalog_error, RuntimeError):
                raise catalog_error
            raise RuntimeError(f"Initial transcript extraction failed: {catalog_error}") from catalog_error
        selected = {"languageCode": "", "name": "Original language"}
        return _result(segments, [], selected, selected, [])


def _fetch_transcript(video_id: str) -> list[dict[str, Any]]:
    """Prefer direct timedtext, then InnerTube/page extraction, then the library."""
    prior_errors: list[Exception] = []
    for fetcher in (_fetch_timedtext_direct, _fetch_innertube_transcript, _fetch_direct_transcript, _fetch_ytdlp_transcript):
        try:
            return fetcher(video_id)
        except YouTubeRateLimitError as error:
            # The Worker and WARP may use different egress paths. Keep the
            # library fallback available before returning a final 429.
            prior_errors.append(error)
            continue
        except (RuntimeError, requests.RequestException) as error:
            prior_errors.append(error)

    try:
        return _youtube_transcript_api_fetch(video_id)
    except TranscriptsDisabled as error:
        raise NoCaptionsError("No public captions are available for this video.") from error
    except NoTranscriptFound as error:
        raise NoCaptionsError("No public captions are available for this video.") from error
    except VideoUnavailable as error:
        raise RuntimeError("The requested video is unavailable or private.") from error
    except RuntimeError as error:
        message = str(error)
        lowered = message.lower()
        prior_messages = " ".join(str(item).lower() for item in prior_errors)
        if any(token in lowered or token in prior_messages for token in ("429", "too many requests", "rate limit", "ratelimit")):
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.") from error
        if "unavailable or private" in prior_messages or "unavailable or private" in lowered:
            raise RuntimeError("The requested video is unavailable or private.") from error
        if any(isinstance(item, NoCaptionsError) for item in prior_errors) and not any(
            isinstance(item, CaptionPayloadError) for item in prior_errors
        ):
            raise NoCaptionsError("No public captions are available for this video.") from error
        if "no element found" in lowered or "empty" in lowered or "xml" in lowered:
            raise YouTubeRateLimitError(
                "YouTube is temporarily limiting transcript requests. Please wait a moment and try again."
            ) from error
        raise
    except Exception as error:
        error_message = str(error)
        lowered = error_message.lower()
        if any(token in lowered for token in ("429", "too many requests", "rate limit", "ratelimit")):
            raise YouTubeRateLimitError("YouTube is temporarily rate-limiting transcript requests.") from error
        if any(isinstance(item, NoCaptionsError) for item in prior_errors) and not any(
            isinstance(item, CaptionPayloadError) for item in prior_errors
        ):
            raise NoCaptionsError("No public captions are available for this video.") from error
        if "no element found" in lowered or "empty" in lowered or "xml" in lowered:
            raise YouTubeRateLimitError(
                "YouTube is temporarily limiting transcript requests. Please wait a moment and try again."
            ) from error
        raise RuntimeError(f"Transcript extraction failed: {error_message}") from error


def get_transcript(url_or_id: str) -> str:
    """Extract and format a transcript as plain text."""
    video_id = extract_video_id(url_or_id)
    transcript = _fetch_transcript_result(video_id)
    return TextFormatter().format_transcript(transcript["segments"])


def get_transcript_payload(url_or_id: str) -> dict[str, Any]:
    """Extract the original-language transcript and return its metadata."""
    video_id = extract_video_id(url_or_id)
    result = _fetch_transcript_result(video_id)
    transcript = result["segments"]
    plain_text = re.sub(r"\s+", " ", TextFormatter().format_transcript(transcript)).strip()
    segments = [
        {
            "text": re.sub(r"\s+", " ", str(item.get("text", ""))).strip(),
            "start": max(0, float(item.get("start", 0) or 0)),
            "duration": max(0, float(item.get("duration", 0) or 0)),
        }
        for item in transcript
    ]
    return {
        "segments": [item for item in segments if item["text"]],
        "plainText": plain_text,
        "originalLanguage": result.get("originalLanguage"),
    }


def main() -> None:
    raw_request = sys.stdin.read().strip()
    try:
        request = json.loads(raw_request) if raw_request.startswith("{") else {"videoId": raw_request}
        url_or_id = str(request.get("videoId", "")).strip()
        print(json.dumps(get_transcript_payload(url_or_id)))
    except ValueError as error:
        print(json.dumps({"kind": "invalid_url", "message": str(error)}))
        raise SystemExit(2)
    except NoCaptionsError as error:
        print(json.dumps({"kind": "no_captions", "message": str(error)}))
        raise SystemExit(2)
    except YouTubeRateLimitError as error:
        print(json.dumps({"kind": "rate_limited", "message": str(error)}))
        raise SystemExit(2)
    except RuntimeError as error:
        message = str(error)
        if message.startswith("Subtitles/Transcripts"):
            kind = "transcripts_disabled"
        elif message.startswith("No transcript") or message.startswith("No public captions"):
            kind = "no_transcript"
        elif message.startswith("The requested video"):
            kind = "video_unavailable"
        elif "empty or corrupted" in message.lower() or "no usable caption" in message.lower():
            kind = "rate_limited"
            message = "YouTube is temporarily limiting transcript requests. Please wait a moment and try again."
        else:
            kind = "upstream_error"
        print(json.dumps({"kind": kind, "message": message}))
        raise SystemExit(2)


if __name__ == "__main__":
    main()
