import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, router } from "./_core/trpc";
import { extractTranscript, parseYoutubeId } from "./transcript";
import { getCachedTranscript, isTranscriptCacheConfigured, setCachedTranscript } from "./transcriptCache";
import { COOKIE_NAME } from "@shared/const";
import { isTurnstileConfigured, verifyTurnstileToken } from "./turnstile";

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  transcript: router({
    lookup: publicProcedure.input(z.object({
      url: z.string().min(1).max(2048),
    })).mutation(async ({ input, ctx }) => {
      if (isTurnstileConfigured()) {
        const token = ctx.req.header("x-turnstile-token") ?? "";
        const verified = await verifyTurnstileToken(token, ctx.req.ip);
        if (!verified) {
          throw new TRPCError({ code: "FORBIDDEN", message: "Please complete the security check before extracting captions." });
        }
      }

      const videoId = parseYoutubeId(input.url);
      const cacheEnabled = isTranscriptCacheConfigured();

      if (!videoId || !cacheEnabled) {
        ctx.res.setHeader("X-Cache-Status", cacheEnabled ? "MISS" : "DISABLED");
        return extractTranscript(input.url);
      }

      try {
        const cached = await getCachedTranscript(videoId);
        if (cached) {
          ctx.res.setHeader("X-Cache-Status", "HIT");
          return cached;
        }
      } catch (error) {
        console.warn("[TranscriptCache] read failed; continuing to YouTube", error instanceof Error ? error.message : "unknown error");
      }

      ctx.res.setHeader("X-Cache-Status", "MISS");
      const result = await extractTranscript(input.url);
      try {
        await setCachedTranscript(videoId, result);
      } catch (error) {
        console.warn("[TranscriptCache] write failed; transcript still returned", error instanceof Error ? error.message : "unknown error");
      }
      return result;
    }),
    localFallback: publicProcedure.input(z.object({
      url: z.string().min(1).max(2048),
    })).mutation(async ({ input }) => {
      const fallbackUrl = (process.env.LOCAL_FALLBACK_URL ?? "").trim().replace(/\/$/, "");
      const sharedSecret = (process.env.LOCAL_FALLBACK_SHARED_SECRET ?? "").trim();
      if (!fallbackUrl || !sharedSecret) {
        throw new TRPCError({ code: "PRECONDITION_FAILED", message: "The Contabo fallback is not configured." });
      }
      try {
        const response = await fetch(`${fallbackUrl}/api/trpc/transcript.lookup?batch=1`, {
          method: "POST",
          headers: { "Content-Type": "application/json", "x-local-fallback-token": sharedSecret },
          body: JSON.stringify({ 0: { json: { url: input.url } } }),
        });
        const raw = await response.text();
        if (!response.ok) throw new Error(`Contabo fallback returned HTTP ${response.status}.`);
        const payload = JSON.parse(raw) as Array<{ result?: { data?: { json?: unknown } }; error?: { json?: { message?: string } } }>;
        const first = payload[0];
        if (first?.error) throw new Error(first.error.json?.message || "The Contabo fallback could not retrieve captions.");
        const result = first?.result?.data?.json;
        if (!result || typeof result !== "object" || !Array.isArray((result as { segments?: unknown }).segments)) {
          throw new Error("The Contabo fallback returned no readable transcript.");
        }
        return result;
      } catch (error) {
        console.warn("[ContaboFallback] request failed", error instanceof Error ? error.message : "unknown error");
        throw new TRPCError({ code: "BAD_GATEWAY", message: "The Contabo fallback could not retrieve captions." });
      }
    }),
    ingestBrowser: publicProcedure.input(z.object({
      url: z.string().min(1).max(2048),
      metadata: z.object({
        videoId: z.string().regex(/^[a-zA-Z0-9_-]{11}$/),
        title: z.string().trim().min(1).max(500),
        channel: z.string().trim().min(1).max(300),
        thumbnailUrl: z.string().url().max(2048),
        durationSeconds: z.number().nonnegative().nullable(),
      }),
      segments: z.array(z.object({
        start: z.number().finite().nonnegative(),
        duration: z.number().finite().nonnegative(),
        text: z.string().trim().min(1).max(4000),
      })).min(1).max(20000),
      originalLanguage: z.object({ code: z.string(), name: z.string(), isOriginal: z.boolean().optional(), isAutoGenerated: z.boolean().optional() }).optional(),
    })).mutation(async ({ input, ctx }) => {
      const videoId = parseYoutubeId(input.url);
      if (!videoId || videoId !== input.metadata.videoId) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "The browser transcript does not match the supplied YouTube video." });
      }

      const result = {
        metadata: { ...input.metadata, videoId },
        segments: input.segments.map(segment => ({ ...segment, text: segment.text.replace(/\s+/g, " ").trim() })).filter(segment => segment.text),
        originalLanguage: input.originalLanguage,
      };
      if (!result.segments.length) {
        throw new TRPCError({ code: "BAD_REQUEST", message: "The browser returned no readable caption text." });
      }

      ctx.res.setHeader("X-Cache-Status", "BROWSER");
      try {
        await setCachedTranscript(videoId, result);
      } catch (error) {
        console.warn("[TranscriptCache] browser write failed; transcript still returned", error instanceof Error ? error.message : "unknown error");
      }
      return result;
    }),
  }),
});

export type AppRouter = typeof appRouter;
