export default function DeepDive() {
  return (
    <section className="deep-dive-section content-container" aria-labelledby="deep-dive-heading">
      <details className="deep-dive">
        <summary id="deep-dive-heading">Understanding YouTube Transcript Formats, WebVTT, and Accessibility</summary>
        <div className="deep-dive-content">
          <p>Available captions can be useful in several different forms. The best format depends on whether the next step is reading, editing, accessibility review, or structured analysis. Understanding the differences between common timed-text formats helps you choose the right export without treating every transcript as interchangeable.</p>
          <h3>How SRT, WebVTT, and JSON differ</h3>
          <p><strong>SRT</strong>, also called SubRip Subtitle, is a compact subtitle format built around numbered cues. Each cue normally contains a sequence number, a start and end time, and one or more lines of text. SRT is widely accepted by video editors and subtitle tools because it is easy to inspect in a text editor and easy to move along a video timeline. Its simplicity is useful, but it also means that styling, positioning, and metadata support are limited compared with newer formats.</p>
          <p><strong>WebVTT</strong> is designed for the web. It uses a cue timing line and can include identifiers, cue settings, regions, and metadata that help a browser position captions or subtitles during playback. WebVTT is especially useful when captions need to be displayed in an HTML video player. A VTT file may contain styling or positioning instructions that should be preserved when it is used in a browser-based player, so converting it to plain text necessarily removes some presentation information.</p>
          <p><strong>JSON</strong> represents transcript segments as structured objects. A segment can contain its text, start time, duration, and other fields needed by an application. JSON is practical for developers, analysts, and content teams building search, indexing, or review tools because software can read fields without parsing human-oriented punctuation. It is not usually a subtitle file by itself; rather, it is a data representation from which another timed format can be generated.</p>
          <h4>Choose the format for the next action</h4>
          <p>Use TXT when the priority is comfortable reading, searching, outlining, or quoting. Use SRT when a video editor needs numbered cues with timing. Use WebVTT when the destination is a web player that understands cue settings. Use JSON when the transcript will be filtered, grouped, indexed, or passed into a technical workflow. Keeping the source URL beside an export makes later verification much easier.</p>
          <h3>Timed captions and accessible video</h3>
          <p>Timed captions connect spoken words to the moment they occur in a video. That connection supports people who are deaf or hard of hearing, viewers watching without sound, language learners, and anyone who benefits from reading while listening. Captions can also make a lecture, interview, or demonstration easier to search and review. Accessibility is not achieved by exporting a file alone: captions should be accurate, synchronized, legible, and complete enough to convey meaningful speech and relevant sound information.</p>
          <p>Caption quality matters for names, technical vocabulary, speaker changes, numbers, and descriptions of important audio. Automatic caption tracks can contain recognition errors, so a responsible workflow includes a review pass against the source video. When captions are published, follow the accessibility requirements and editorial standards of the destination platform, institution, or organization. A transcript is a useful working document, but it should not be presented as an official or perfect record without review.</p>
          <h3>Localizing captions for a global audience</h3>
          <p>Localization begins with a clean source transcript and a clear understanding of the audience. Preserve names, measurements, dates, idioms, and culturally important references before adapting the wording. A human reviewer can decide whether a phrase should be translated literally, explained, or replaced with an equivalent that makes sense in the target region. Timing may also need adjustment because translated languages can expand or contract compared with the source language.</p>
          <h4>A careful workflow without third-party AI processing</h4>
          <p>A privacy-conscious localization workflow can keep the source material in a local document. First, review and segment the original captions. Next, translate the text using an approved human or local process, then compare the translated lines with the original timing. Finally, check reading speed, line length, punctuation, and proper names before exporting a reviewed subtitle file. This approach avoids sending transcript content to an unapproved third-party AI processor and keeps editorial responsibility visible.</p>
          <p>For international publishing, maintain a small language glossary and record which version was reviewed. Treat each translated file as an editorial adaptation rather than an invisible replacement of the original. Preserving the original-language source, the target-language file, and the video URL gives collaborators a clear audit trail and makes corrections easier when the source changes.</p>
        </div>
      </details>
    </section>
  );
}
